<h1 align="center">Some usefull methods</h1>

 <h2>1. Reshape function</h2> 
allows you to change the shape of an array without changing its data. This is useful for organizing data into different dimensions, such as converting a one-dimensional array into a two-dimensional array.







In [5]:
# Create a 1D array with 6 elements
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
# Reshape it to a 2D array with 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


 <h2>2. Max function</h2> 


In [8]:
print(arr.max())


6


 <h2>3. Min function</h2> 


In [ ]:
print(arr.min())

1


 <h2>4. Argmax and argmin</h2>
 use to find index of the max and min 


In [10]:
print(arr.argmax())

5


In [11]:
print(arr.argmin())

0


 <h2>5. Flattend func</h2>
 it is used to convert 2d or 3d array into 1d


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = arr.flatten()
print(arr) #original does not changes
print(arr2)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2 = arr.flatten()
print(arr) #original does not changes
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


 <h2>6. stack func</h2>
  allows you to  stack (concatenate) two or more arrays along their second dimension (columns). It combines arrays side by side, which is particularly useful for organizing or appending data in a structured way
  
<b>hstack</b> for horizontal<br>
<b>vstack is by default</b> for vertically<br>
<b>dstack</b> for hight

In [ ]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# stack the arrays
result = np.stack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontally stack the arrays
result = np.hstack((arr1, arr2))
print(result)


[1 2 3 4 5 6]


In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontally stack the arrays
result = np.dstack((arr1, arr2))
print(result)


[[[1 4]
  [2 5]
  [3 6]]]


In [33]:
# Create two 2D arrays with the same number of rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# stack the arrays
result = np.stack((arr1, arr2))
print(result)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
# Create two 2D arrays with the same number of rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# stack the arrays
result = np.hstack((arr1, arr2))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [35]:
# Create two 2D arrays with the same number of rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# stack the arrays
result = np.dstack((arr1, arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


<h2>difference between flatten and hstack</h2>

The flatten and hstack functions in NumPy both work with arrays, but they serve different purposes and operate differently:

flatten(): This function is used to convert a multi-dimensional array into a one-dimensional array. It “flattens” all elements into a single, continuous row, regardless of the array’s original shape.

hstack(): This function is used to horizontally stack (concatenate) multiple arrays, combining them side-by-side along columns. The arrays must have the same number of rows to be stacked horizontally.

 <h2>7. split func</h2>

The  function in NumPy is used to split an array  i.e., along its columns. or rows It divides an array into multiple sub-arrays, allowing you to separate data horizontally.

<b>Hsplit and split is same it divide an array into multiple sub-arrays</b><br>
<b>vsplit  into multiple sub-arrays but it works on 2d arrays</b><br>
<b>dsplit  into multiple sub-arrays but it works on 3d arrays</b><br>

In [ ]:
arr = np.arange(10)
arr = np.split(arr , 2)
print(arr)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [58]:
arr = np.arange(10)
arr = np.hsplit(arr , 2)
print(arr)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [62]:

# Create a 2D array with 4 columns
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Split the array into 2 equal parts
split_arr = np.vsplit(arr, 2)
split_arr


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [ ]:
# Create a 2D array with 4 columns
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]] ,ndmin=3)
arr
# Split the array into 2 equal parts
split_arr = np.dsplit(arr, 2)
split_arr


[array([[[ 1,  2],
         [ 5,  6],
         [ 9, 10]]]),
 array([[[ 3,  4],
         [ 7,  8],
         [11, 12]]])]

 <h2>8. Copy func</h2>
create a copy of the array

In [29]:
arr2 = np.copy(arr)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

 <h2>9. View func</h2>

The view function in NumPy allows you to create a new view of an existing array without copying the data. This means that changes made to the view will affect the original array, and vice versa. It's particularly useful when you need to work with or manipulate an array's data in a different way but don't want to create an entirely new copy in memory.

In [30]:

arr = np.array([1, 2, 3, 4])
arr_view = arr.view()

# Modify the view
arr_view[1] = 20

print("Original array:", arr)
print("View of the array:", arr_view)


Original array: [ 1 20  3  4]
View of the array: [ 1 20  3  4]


 <h2>9. Nditer func</h2>

 This is used to iterate over multiple dimesions arrays.


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for z in arr:
    for y in z:
        print(y)

1
2
3
4
5
6
7
8
9


In [8]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9


 <h2>9. Concentenate func</h2>
 use to merge two arrays
in case of 2d arrays you can control the axis to which you want to merge ok 0 for y axis, 1 for x axis (y axis is by default)

In [11]:
arr1 = np.arange(1, 10)
arr2 = np.arange(21)
arr3 = np.concatenate([arr1, arr2])
print(arr3)

[ 1  2  3  4  5  6  7  8  9  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14
 15 16 17 18 19 20]


In [22]:
arr1 = np.arange(1, 7).reshape(3,2)
arr2 = np.arange(7, 13).reshape(3,2)

arr3 = np.concatenate([arr1, arr2] , axis=1)
print(arr3)


[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


 <h2>10. Shuffle func</h2>
use to Shuffle

In [73]:
arr = np.array([1, 2, 3, 4])
np.random.shuffle(arr)
print(arr)

[3 1 4 2]


 <h2>10. Unique func</h2>
remove the repeated elements 

In [76]:
arr = np.array([1,4,2, 3,4,5,4,5,4])

unique_elements = np.unique(arr)

print("Unique elements in the array:", unique_elements)


Unique elements in the array: [1 2 3 4 5]


In [78]:
arr = np.array([1, 2, 3,4,5,4,5,4])

unique_elements = np.unique(arr , return_index=True)

print("Unique elements in the array:", unique_elements)


Unique elements in the array: (array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4]))


In [79]:
arr = np.array([1, 2, 3,4,5,4,5,4])

unique_elements = np.unique(arr , return_index=True , return_counts=True)

print("Unique elements in the array:", unique_elements)


Unique elements in the array: (array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4]), array([1, 1, 1, 3, 2]))


 <h2>11. Resize func</h2>
use to resize the array

In [83]:
arr = np.array([1,2,3,4,5,6])
arr2 = np.resize(arr , (2,3))
arr2

array([[1, 2, 3],
       [4, 5, 6]])