<h1 align="center">How to create arrays 
</h1>


first import numpy

In [ ]:
import numpy as np

<h2>Ways to create arrays</h2>

<h3 >1 .Using python list<h3>

In [2]:
list1 = [1,2,3,4,5,6,7,8]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
type(arr)

numpy.ndarray

2d list 

In [12]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list2)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h3>2 .Using arange<h3>

In [21]:
# for x in range(1,10):
#     print(x)

arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr = np.arange(1,11,2)
arr


array([1, 3, 5, 7, 9])

<h3>3 .Specific types of array<h3>

Zero arrays 

In [36]:
arr = np.zeros(5)
arr


array([0., 0., 0., 0., 0.])

In [16]:
arr = np.zeros((5,5))
arr


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
int_array = np.zeros(5, dtype=int)
print(int_array)

[0 0 0 0 0]


Ones array

In [13]:
arr =  np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [17]:
arr =  np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
int_array = np.ones(5, dtype=int)
print(int_array)

[1 1 1 1 1]


Identity matrix

In [ ]:
arr = np.eye(3 )
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<h3>4 .Using linspace<h3>
<p>linspace is a function in the NumPy library that generates an array of evenly spaced numbers over a specified interval</p>


<h3>Syntax :</h3> numpy.linspace(start, stop, num=50)


In [58]:
arr = np.linspace(1,2,100)
arr



array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

<h3>5 .Random array<h3>

In [77]:
# random number from 0 to 1
arr = np.random.rand(5)
arr

array([0.83340878, 0.70021052, 0.23768043, 0.08927703, 0.0253015 ])

In [67]:
# if you give two values then it will be consider as row and columns
arr = np.random.rand(5,5)
arr = np.array(arr , dtype="float")
arr

array([[0.22903301, 0.31964598, 0.37759377, 0.08063366, 0.20884742],
       [0.78149026, 0.7744319 , 0.03154539, 0.77760336, 0.89198853],
       [0.65645878, 0.56559535, 0.28771595, 0.71376576, 0.69391279],
       [0.85946572, 0.46567915, 0.64198272, 0.90677678, 0.04464986],
       [0.93327026, 0.92144003, 0.16776911, 0.77849404, 0.72258847]])

In [75]:
# randint function is used to generate random number from the range of numbers the first parameter is starting range of the
# number and the second parameter is ending range of the number and the third parameter is how many numbers you want to 
# generate 

arr = np.random.randint(1,50,10)
arr

array([41, 48, 11, 19, 46, 20, 23, 37, 34, 26], dtype=int32)

In [86]:
# generate random numbers closest to the zero and can be negative numbers a
arr =  np.random.randn(5)
arr

array([-0.46039023, -0.83306037, -0.75092986, -0.47185133, -1.19272373])

<h3>6 .Structured array<h3>

In [104]:
# dtdtype="object" can also be used but then you have to do indexing one by one
arr= np.array([(1,"uzair",20),(2,"rafay",22),(3,"aqib",23)] , dtype=[("id" ,int),("name" ,"U10"),("age" ,int)])
print(arr)

[(1, 'uzair', 20) (2, 'rafay', 22) (3, 'aqib', 23)]


In [ ]:
arr["name"]


array([20, 22, 23])

In [21]:
arr= np.array([(1,"uzair",20),(2,"rafay",22),(3,"aqib",23)] , dtype=object)
print(arr)

[[1 'uzair' 20]
 [2 'rafay' 22]
 [3 'aqib' 23]]


In [24]:
print(arr[0:3,1])

['uzair' 'rafay' 'aqib']
