<h1 align="center">How to create arrays 
</h1>


first import numpy

In [2]:
import numpy as np


<h2>Ways to create arrays</h2>

<h3 >1 .Using python list<h3>

In [4]:
list1 = [1,2,3,4,5,6,7,8,]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

2d list 

In [6]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(list2)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h3>2 .Using arange<h3>

In [8]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.arange(1,11 , 2)
arr


array([1, 3, 5, 7, 9])

<h3>3 .Specific types of array<h3>

Zero arrays 

In [10]:
arr = np.zeros(5)
arr


array([0., 0., 0., 0., 0.])

In [16]:
arr = np.zeros((5,5))
arr


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
int_array = np.zeros(5, dtype=int)
print(int_array)

[0 0 0 0 0]


Ones array

In [13]:
arr =  np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [17]:
arr =  np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
int_array = np.ones(5, dtype=int)
print(int_array)

[1 1 1 1 1]


Identity matrix

In [23]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h3>4 .Using linspace<h3>
<p>linspace is a function in the NumPy library that generates an array of evenly spaced numbers over a specified interval</p>


<h3>Syntax :</h3> numpy.linspace(start, stop, num=50)


In [22]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

<h3>5 .Random array<h3>

In [ ]:
# random number from 0 to 1
arr = np.random.rand(5)
arr

array([0.07424235, 0.15846081, 0.26082255, 0.6283872 , 0.8874719 ])

In [ ]:
# if you give two values then it will be consider as row and columns
arr = np.random.rand(5,5)
arr

array([[0.12161186, 0.67355355, 0.86608722, 0.99759212, 0.29331172],
       [0.42664075, 0.91805592, 0.6578502 , 0.02048761, 0.43611701],
       [0.13917511, 0.01195989, 0.71470912, 0.92531459, 0.72951646],
       [0.40904239, 0.2350791 , 0.92462755, 0.41871309, 0.45244856],
       [0.76690989, 0.07178081, 0.87474248, 0.72092878, 0.62065076]])

In [7]:
# randint function is used to generate random number from the range of numbers the first parameter is starting range of the
# number and the second parameter is ending range of the number and the third parameter is how many numbers you want to 
# generate 

arr = np.random.randint(1,50,10)
arr

array([ 4, 15, 33, 46, 31,  1,  5, 42, 43, 18], dtype=int32)

In [ ]:
# generate random numbers closest to the zero and can be negative numbers a
arr =  np.random.randn(5)
arr

array([ 0.77660024, -0.93074211,  0.3147201 ,  0.38023664,  0.67056436])

<h3>6 .Structured array<h3>

In [18]:
arr= np.array([(1,"uzair",20),(2,"rafay",22),(3,"aqib",23)] , dtype=[("id" ,int),("name" ,"U10"),("age" ,int)])
print(arr)

[(1, 'uzair', 20) (2, 'rafay', 22) (3, 'aqib', 23)]


In [20]:
arr["name"]

array(['uzair', 'rafay', 'aqib'], dtype='<U10')

In [21]:
arr= np.array([(1,"uzair",20),(2,"rafay",22),(3,"aqib",23)] , dtype=object)
print(arr)

[[1 'uzair' 20]
 [2 'rafay' 22]
 [3 'aqib' 23]]


In [24]:
print(arr[0:3,1])

['uzair' 'rafay' 'aqib']
