<h1 align="center">numpy.isnan() </h1>


In [1]:
import numpy as np

The np.isnan() function is used to identify NaN (Not a Number) values in an array. It returns a boolean array of the same shape as the input, where each element indicates whether the corresponding element in the input is NaN
(ya func check krta ha ka hmary array ma koi nan value ha agr ho ge to wha pa ya true return kr dta ha 
)

In [2]:

# Create an array with NaN values
data = np.array([1, 2, np.nan, 4, np.nan, 6])

# Check for NaN values
nan_mask = np.isnan(data)

print(nan_mask)  # Output: [False False  True False  True False]


[False False  True False  True False]


In [3]:

# Original array
data = np.array([1, 2, np.nan, 4, np.nan, 6])

# Filter out NaN values
clean_data = data[~np.isnan(data)]  # Using the inverse mask to select non-NaN values

print(clean_data)  # Output: [1. 2. 4. 6.]


[1. 2. 4. 6.]


<h1 align="center">nan_to_num() </h1>


In NumPy, if you want to replace NaN (Not a Number) values with a specific number, you can use the np.nan_to_num() function. This function is useful for data cleaning and preprocessing, especially when you want to perform calculations on arrays without the interference of NaN values.
(is sa hm jo nan value ha usko replace kr laita ha apni desired value sa)

<h2>Syntax</h2>

numpy.nan_to_num(x, copy=True, nan=0.0, posinf=None, neginf=None)

x: Input array, which can be a NumPy array or any structure that can be converted to a NumPy array.

copy: If True, a new array is created; if False, it attempts to modify the input array in place (if possible).

nan: The value to replace NaN (default is 0.0).

posinf: The value to replace positive infinity (default is None, meaning it will remain unchanged).

neginf: The value to replace negative infinity (default is None, meaning it will remain unchanged).

In [4]:

# Create an array with NaN values
data = np.array([1, 2, np.nan, 4, np.nan, 6])

# Replace NaN values with 0
cleaned_data = np.nan_to_num(data)

print(cleaned_data)  # Output: [1. 2. 0. 4. 0. 6.]


[1. 2. 0. 4. 0. 6.]


In [5]:

# Create an array with NaN values
data = np.array([1, 2, np.nan, 4, np.nan, 6])

# Replace NaN values with -1
cleaned_data = np.nan_to_num(data, nan=-1)

print(cleaned_data)  # Output: [ 1.  2. -1.  4. -1.  6.]


[ 1.  2. -1.  4. -1.  6.]


In [6]:


# Create an array with NaN and infinity values
data = np.array([1, 2, np.nan, np.inf, -np.inf, 6])

# Replace NaN with 0, positive infinity with 999, and negative infinity with -999
cleaned_data = np.nan_to_num(data, nan=0, posinf=999, neginf=-999)

print(cleaned_data)  # Output: [  1.   2.   0. 999. -999.   6.]


[   1.    2.    0.  999. -999.    6.]
