In [2]:
import numpy as np

<h1 align="center">numpy.savetxt() </h1>

This a function used to save a NumPy array to a text file. It allows you to specify the format of the data and add delimiters, headers, and footers. This function is useful when you want to save data in a readable text format (like .txt or .csv).

<h2>Basic Syntax</h2>

numpy.savetxt(fname, X, delimiter=' ', fmt='%s', header='', footer='', comments='# ')


fname: The name of the file to save data in. You can use a .txt or .csv file extension.

X: The array you want to save.

delimiter: The string used to separate values (e.g., , for CSV).

fmt: Format string for each element in the array. Common options:
'%d': Integer format
'%.2f': Float with 2 decimal places
'%s': String

header: String that will be written at the beginning of the file as a header.

footer: String that will be written at the end of the file as a footer.

comments: String that marks the start of a comment in the header or footer. By default, this is #.

In [ ]:
# Simple data

data =  np.array(([1,2,3],[4,5,6],[7,8,9]))

np.savetxt('savetxt.txt', data, delimiter=',' ,fmt="%d")


In [ ]:
# with header and footer
np.savetxt(
    'data_with_header_footer.txt', 
    data, 
    delimiter=',', 
    fmt='%.2f', 
    header='Sample Data with Header', 
    footer='End of Data'
)


In [ ]:
# mixed data
data_mixed = np.array([(1, 'Alice', 90.5), (2, 'Bob', 85.0), (3, 'Charlie', 88.0)])
print(data_mixed)
np.savetxt('data_mixed.txt', data_mixed, fmt='%s', delimiter=',')


[['1' 'Alice' '90.5']
 ['2' 'Bob' '85.0']
 ['3' 'Charlie' '88.0']]


<h1 align="center">numpy.save() </h1>

In NumPy, the np.save() function is used to save arrays to a binary .npy file, which preserves the array’s data type and shape. This format is more efficient than saving data to text files, as it’s faster to load and saves space.
(ya  method data ko .npy or .npz files ma save krna ka leya use hota ha binary fromat ma ok)


<h2>Basic Syntax</h2>

numpy.save(file, arr, allow_pickle=True)

file: The file name or file path to save the array. By convention, .npy is used as the extension (e.g., 'data.npy').

arr: The array to be saved.

allow_pickle: If True, allows saving objects like lists and dictionaries along with the array. Default is True.


In [14]:
# Create a sample array
data = np.array([1, 2, 3, 4, 5])

# Save the array to a file named 'data.npy'
np.save('data.npy', data)


In [10]:
# Load the array from the file
loaded_data = np.load('data.npy')
print(loaded_data)


[1 2 3 4 5]


In [4]:
# Create a 2D array
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save the 2D array
np.save('data_2d.npy', data_2d)


In [ ]:
# Create multiple arrays
data1 = np.array([1, 2, 3])
data2 = np.array([[4, 5, 6], [7, 8, 9]])

# Save multiple arrays in a single .npz file
np.savez('multiple_data.npz', array1=data1, array2=data2)


In [9]:
loaded = np.load('multiple_data.npz')
print(loaded['array1'])
print(loaded['array2'])


[1 2 3]
[[4 5 6]
 [7 8 9]]


In [ ]:
data_with_object = np.array([{"name": "Alice", "score": 90}, {"name": "Bob", "score": 85}])

# Save with pickle enabled
np.save('data_with_object.npy', data_with_object , allow_pickle=True)


In [15]:
loaded_data = np.load('data_with_object.npy', allow_pickle=True)
print(loaded_data)


[{'name': 'Alice', 'score': 90} {'name': 'Bob', 'score': 85}]
