<h1>Matrix</h1>

In [1]:
# # matrix

import numpy as np

# A = np.array([[1, 2, 3], [4, 5, 6]])
# B = np.array([[7, 8], [9, 10], [11, 12]])

# # Addition
# print(np.add(A, B))

# # Subtraction
# print(np.subtract(A, B))

# # Multiplication
# print(np.multiply(A, B))

# # Transpose
# print(np.transpose(A))

# # Determinant
# print(np.linalg.det(A))

# # Inverse

# try:
#     print(np.linalg.inv(A))
# except np.linalg.LinAlgError:
#     print("The matrix is not invertible")
#     exit()

# # Rank

# print(np.linalg.matrix_rank(A))

# # Trace

# print(np.trace(A))

# # Eigenvalues and eigenvectors

# eigenvalues, eigenvectors = np.linalg.eig(A)
# print("Eigenvalues:", eigenvalues)
# print("Eigenvectors:", eigenvectors)

# # Singular Value Decomposition

# U, S, V = np.linalg.svd(A)
# print("U:", U)
# print("S:", S)
# print("V:", V)

# # Diagonalization

# D = np.diag(S)
# print("Diagonalized matrix:", U @ D @ V)

# # QR decomposition

# Q, R = np.linalg.qr(A)
# print("Q:", Q)
# print("R:", R)

# # Singular value decomposition

# U, S, V = np.linalg.svd(A)
# print("U:", U)
# print("S:", S)
# print("V:", V)





In [2]:
A = np.matrix([[1, 2], [4, 5]])
B = np.matrix([[7, 8], [9, 10]])
print(A)
print(B)
print()
# multiplication
print(np.multiply(A, B))
print()
print(A*B)
print()
print(np.dot(A, B))

[[1 2]
 [4 5]]
[[ 7  8]
 [ 9 10]]

[[ 7 16]
 [36 50]]

[[25 28]
 [73 82]]

[[25 28]
 [73 82]]


In [3]:
A = np.array([[1, 2], [4, 5]])
B = np.array([[7, 8], [9, 10]])

# Addition

print(np.multiply(A, B))

[[ 7 16]
 [36 50]]


In [4]:
arr1 = np.matrix([[1, 2, 3], [4, 5,6]])
arr2 = np.matrix([[7, 8, 9], [10, 11,12]])
print(arr1)
print(arr2)

print()

# Addition
print(arr1 + arr2)
print()
# Addition
print(np.add(arr1, arr2))
print()

# Subtraction

print(arr1 - arr2)
print()

# Subtraction
print(np.subtract(arr1, arr2))
print()

# multiplication
# print(arr1 * arr2)
# print() # it will give the error bcz matrix cannot be multiply using * operator

# Multiplication
print(np.multiply(arr1, arr2))
print()


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[[ 8 10 12]
 [14 16 18]]

[[ 8 10 12]
 [14 16 18]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[ 7 16 27]
 [40 55 72]]



In [5]:
arr1 = np.array([[1, 2, 3], [4, 5,6]])
arr2 = np.array([[7, 8, 9], [10, 11,12]])
print(arr1)
print(arr2)

print()

# addition
print(arr1 + arr2)
print()
# Addition
print(np.add(arr1, arr2))
print()
# Subtraction

print(arr1 - arr2)
print()

# Subtraction
print(arr1 - arr2)
print()
# multiplication
print(arr1 * arr2)
print() # but here is did not give error bcz array can be multiplied using * operator

# Multiplication
print(np.multiply(arr1, arr2))
print()



[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[[ 8 10 12]
 [14 16 18]]

[[ 8 10 12]
 [14 16 18]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[ 7 16 27]
 [40 55 72]]

[[ 7 16 27]
 [40 55 72]]



In [6]:
arr1 = np.matrix([[1, 2, 3], [4, 5,6]])
arr2 = np.matrix([[7, 8, 9], [10, 11,12], [13, 14, 15]])
arr3 = np.array([[1, 2, 3], [4, 5,6]])
arr4 = np.array([[7, 8, 9], [10, 11,12], [13, 14, 15]])

print(arr1)
print(arr2)
print()
print(arr3)
print(arr4)


# multiplication
# print(np.dot(arr1, arr2))


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [10]:
# other matrix functions
# determinate
arr1 = np.array([[1, 2, 3], [4, 5,6]])
arr2 = np.array([[7, 8, 9], [10, 11,12]])


arr3 = np.array([[1, 2], [4, 5]])
print(np.linalg.det(arr3))

# inverse

try:
    print(np.linalg.inv(arr1))
except np.linalg.LinAlgError:
    print("The matrix is not invertible")

# # rank

print(np.linalg.matrix_rank(arr1))

# # trace

print(np.trace(arr1))

# # eigenvalues and eigenvectors
# eigenvalues
arr = np.array([[1, 2], [3, 4]])
print(np.linalg.eigvals(arr))
# eigenvectors
print(np.linalg.eig(arr))



-2.9999999999999996
The matrix is not invertible
2
6
[-0.37228132  5.37228132]
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
