In [19]:
import numpy as np

<h1> Insert Functions</h1>
first parameter is the array in which to insert and the second parameter is the index at which you want to insert the third parameter is the value that you want to insert

In [20]:
arr = np.array([1, 2, 3, 4])

# Insert an element at the beginning
arr = np.insert(arr, 0, 5)
arr

array([5, 1, 2, 3, 4])

In [21]:
arr = np.array([1, 2, 3, 4])

# Insert multiple element at the beginning

arr = np.insert(arr, 0, [5, 6, 7])
arr

array([5, 6, 7, 1, 2, 3, 4])

In [22]:
# append

arr = np.append(arr, 5)
arr

array([5, 6, 7, 1, 2, 3, 4, 5])

In [23]:
#  now 2d array 

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Insert an element at the beginning of the first row
arr_2d = np.insert(arr_2d, 0, 0, axis=0)

arr_2d

array([[0, 0, 0],
       [1, 2, 3],
       [4, 5, 6]])

In [24]:
#  now append

arr_2d = np.append(arr_2d, [[7, 8, 9]], axis=0)

arr_2d

array([[0, 0, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h1> delete Functions</h1>


In [25]:
# delete functions
arr = np.array([1,2,3,4,5,6,7,8])

# delete element at index 4

arr = np.delete(arr, 4)
arr

array([1, 2, 3, 4, 6, 7, 8])