In [1]:
import numpy as np

<h1>Numpy Arrays Operations</h1>


In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [10]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
arr / arr

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_43488\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr1 = np.sqrt(arr)
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [13]:
arr1 = np.exp(arr)
arr1

array([ 1.        ,  2.71828183,  4.11325038,  5.65223367,  7.3890561 ,
        9.35646902, 11.58243519, 14.09403011, 16.91882868, 20.08553692,
       23.62434292])

In [14]:
arr1 = np.sin(arr)
arr1

array([ 0.        ,  0.84147098,  0.98776595,  0.98702664,  0.90929743,
        0.78674913,  0.63815764,  0.47577184,  0.30807174,  0.14112001,
       -0.02068353])