In [1]:
import numpy as np

<h1>Math functions</h1>

In [3]:
arr = np.arange(1,6)
arr2 = np.arange(6,11)
print(arr)
print(arr2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [7]:
np.add(arr, arr2)

array([ 7,  9, 11, 13, 15])

In [8]:
np.subtract(arr, arr2)

array([-5, -5, -5, -5, -5])

In [5]:
np.mod(arr,arr2)

array([1, 2, 3, 4, 5])

In [9]:
np.reciprocal(arr,arr2)

array([1, 0, 0, 0, 0])

In [8]:
np.power(arr,arr2)

array([      1,     128,    6561,  262144, 9765625])

In [9]:
np.multiply(arr, arr2)

array([ 6, 14, 24, 36, 50])

In [10]:
np.divide(arr, arr2)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [13]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [14]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [15]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

<h1>Statistical Operations</h1>

In [17]:
print(np.mean(arr))

3.0


In [18]:
print(np.median(arr))

3.0


In [19]:
print(np.std(arr))

1.4142135623730951


<a href="mean_median_std.md">Explanation on Mean , Median and Standard Deviation(std)</a>

<h1>Linear Algebra</h1>

<h2>dot function</h2>
The dot function in NumPy performs the dot product of two arrays. The dot product is a fundamental operation in linear algebra, often used in fields like machine learning, physics, and engineering. It works differently depending on the dimensions of the input arrays:

For 1D arrays, it calculates the inner product.
For 2D arrays (matrices), it performs matrix multiplication.
For higher-dimensional arrays, it generalizes to more complex tensor products.

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate dot product
result = np.dot(a, b)
print("Dot product:", result)

Dot product: 32


In [21]:
# Create two 2D arrays (matrices)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Calculate dot product (matrix multiplication)
result = np.dot(a, b)
print("Dot product:\n", result)

Dot product:
 [[19 22]
 [43 50]]


<a href="multiply_2d.md">Explanation on Multiplication of 2d matrix</a> 

<h2>Use of @</h2>
it is short hand for matrix multiplication

In [ ]:

# Define the matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Use @ for matrix multiplication
result = A @ B
print(result)


[[19 22]
 [43 50]]


<h2>Linear Equation solve(linalg.solve)</h2>

In [ ]:

# Coefficient matrix A
A = np.array([[2, 3], 
              [4, 1]])

# Right-hand side vector b
b = np.array([5, 11])

# Solve for x
solution = np.linalg.solve(A, b)

print("Solution:", solution)


Solution: [ 2.8 -0.2]


<a href="Exp_linalg_solve.md">Explanation of linear solution</a>