In [1]:
import numpy as np

Note : indexing is same as list list indexing in python but do remember one thing one you create a slice of array and make changes in it , it will effect the original array which is not a case in python list so if you want to change something in a array with out changing original array you have to make a copy of the original array using copy() method

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [5]:
arr[1:6] = 10

In [6]:
arr

array([ 0, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

now using copy() method

In [7]:
arr2 = arr.copy()


In [8]:
arr2

array([ 0, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

In [11]:
arr2[1:6] = 100

In [13]:
arr2

array([  0, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [14]:
arr

array([ 0, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10])

<h1>Indexing</h1>

using double brackets

In [16]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(arr[0][1])

2


using commas

In [20]:
print(arr[0,1])

2


Slicing

In [21]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

Conditional Slicing

In [24]:
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [26]:
bool_arr = arr > 5

In [27]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [28]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [29]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [30]:
arr[arr<4]

array([0, 1, 2, 3])

In [31]:
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])