In [1]:
import numpy as np

<h1>Where func</h1>

It is used to find that specific elements repeats where in the array it returns the index where the element repeats

In [11]:
arr = np.array([1,2,3,4,5,1,2,3,4,2,2,3,4,2])
where = np.where( arr == 2)
print(where)

(array([ 1,  6,  9, 10, 13]),)


In [13]:
arr = np.array([1,2,3,4,5,1,2,3,4,2,2,3,4,2])
where = np.where( arr%2 == 0)
print(where)

(array([ 1,  3,  6,  8,  9, 10, 12, 13]),)


In [24]:
arr = np.array([1,2,3,4,5,6])   
arr = np.where(arr>3,1,0)
print(arr)

[0 0 0 1 1 1]


<h1>Sort func</h1>

It is used to sort arrays

In [21]:
arr = np.array([8,9,1,3,6,2])
arr2 = np.sort(arr)
print(arr2)

[1 2 3 6 8 9]


In [ ]:

arr = np.array([8, 9, 1, 3, 6, 2])
arr2 = sorted(arr, reverse=True)  
arr3 = np.array(arr2)           

print("Descending Order:", arr3)


Descending Order: [9 8 6 3 2 1]


<h1>Searchsorted  func</h1>

It works on sorted array which you want to insert a element in the array it will tell you at what index you should insert it

In [22]:
arr = np.array([8,9,1,3,6,2])
arr2 = np.sort(arr)
arr2

array([1, 2, 3, 6, 8, 9])

In [23]:
axis = np.searchsorted(arr2,4)
print(axis)

3


<h1>filtered  array</h1>

It is used to filter the array


In [25]:

arr = np.array([1,2,3,4,5,6,7,8,9])
arr = arr[arr>5]
print(arr)


[6 7 8 9]


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr2 = arr[arr%2!=0]

print(arr2)

[1 3 5 7 9]


In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr3 = arr[arr%3==0]

print(arr3)

[3 6 9]


In [32]:
arr = np.array([1,2,3,4,5])
f = [True,False,False,True,False,]
print(arr[f])

[1 4]


<h1>unique  array</h1>
# It is used to get the unique elements of the array



In [29]:
arr = np.array([1,2,2,3,4,4,5,6 ,7,8,8,9])
arr = np.unique(arr)
print(arr)

[1 2 3 4 5 6 7 8 9]


<h1>ravel  array</h1>
# It is used to get the ravelled array
it is used to flatten the multi-dimensional into a single dimensional


In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr = arr.ravel()
print(arr)


[1 2 3 4 5 6 7 8 9]
